apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: test-service
  namespace: default
spec:
  template:
    spec:
      selector:
        created-by: kubeless
        function: get-python
      type: LoadBalancer
      ports:
        - name: http
          port: 80
          targetPort: 8080
---
apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: test-service
spec:
  clusterNames:
  - cluster1
  - cluster2

