apiVersion: core.federation.k8s.io/v1alpha1
kind: FederatedTypeConfig
metadata:
  name: functions.kubeless.io
  namespace: federation-system
spec:
  target:
    version: v1beta1
    kind: Function
  namespaced: true
  comparisonField: Generation
  propagationEnabled: true
  template:
    group: federation.kubeless.io
    version: v1alpha1
    kind: FederatedFunction
  placement:
    kind: FederatedFunctionPlacement
